(function(){
var h=false,i=null,m=true,o=document,r=navigator,s=window;
function aa(){var a=o.cookie,b=Math.round((new Date).getTime()/1000),c=s.google_analytics_domain_name,d=typeof c=="undefined"?ba("auto"):ba(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,g=a.indexOf("__utmc="+d)>-1,j,k={};if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&g?j[3]+"":s&&s.gaGlobal&&s.gaGlobal.sid?s.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=m}else{k.sid=s&&s.gaGlobal&&s.gaGlobal.sid?s.gaGlobal.sid:b+"";k.vid=s&&s.gaGlobal&&s.gaGlobal.vid?
s.gaGlobal.vid:(ca()^da()&2147483647)+"."+b;k.from_cookie=h}k.dh=d;k.hid=s&&s.gaGlobal&&s.gaGlobal.hid?s.gaGlobal.hid:ca();s.gaGlobal=k;return k}function ca(){return Math.round(Math.random()*2147483647)}
function da(){var a=o.cookie?o.cookie:"",b=s.history.length,c,d,e=[r.appName,r.version,r.language?r.language:r.browserLanguage,r.platform,r.userAgent,r.javaEnabled()?1:0].join("");if(s.screen)e+=s.screen.width+"x"+s.screen.height+s.screen.colorDepth;else if(s.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=o.referrer?o.referrer:"";c=e.length;while(b>0)e+=b--^c++;return ea(e)}
function ea(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function ba(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=o.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return ea(a.toLowerCase())};var fa={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type",google_page_url:"url"},ga={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",
google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"};function ha(){}ha.prototype.Db=function(){};ha.prototype.Eb=function(){};ha.prototype.Cb=function(){};var t=i;function ia(a){t&&t.Db(a)}function ja(a){t&&t.Eb(a)}function ka(a){t&&t.Cb(a)}function u(){this.F=this.sb();this.ia=h;if(!this.F){this.ia=this.Va();this.ia||ja("Browser does not allow cookies")}}u.prototype.$="__gads=";u.prototype.N="GoogleAdServingTest=";u.prototype.cb=function(){return this.F};
u.prototype.setCookieInfo=function(a){this.A=a._cookies_[0];if(this.A!=i){this.F=this.A._value_;this.Bb()}};u.prototype.Ya=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
u.prototype.Xa=function(a){if(this.F!=i||!this.ia){ia("Skipping fetch cookie call");return}var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+la(a)+"&domain="+la(c);ia("Issuing a fetch cookie call with <a href='"+d+"'>"+d+"</a>");document.write("<"+b+' src="'+d+'"></'+b+">")};
u.prototype.Va=function(){document.cookie=this.N+"Good";var a=this.ua(this.N),b=a=="Good";if(b){var c=this.Ya(-1);document.cookie=this.N+"; expires="+c.toGMTString()}return b};u.prototype.sb=function(){var a=this.ua(this.$);a!=i?ia("Read first party cookie: "+a):ja("No first party cookie found");return a};u.prototype.ua=function(a){var b=document.cookie,c=b.indexOf(a),d=i;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};
u.prototype.Bb=function(){if(this.A==i)ja("Skipping cookie creation: no cookie info");else if(this.F==i)ka("Skipping cookie creation: no cookie value");else{var a=new Date;a.setTime(1000*this.A._expires_);var b=this.A._domain_,c=this.$+this.F+"; expires="+a.toGMTString()+"; path="+this.A._path_+"; domain=."+b;document.cookie=c;ia("Written cookie: "+c)}};
function ma(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=i}return b.toString()}else if(na("msie")&&!window.opera){var c=i;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=i){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var oa=oa||{},v=this,qa=function(a,b,c){var d=a.split("."),e=c||v,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);while(d.length&&(f=d.shift()))if(!d.length&&pa(b))e[f]=b;else e=e[f]?e[f]:(e[f]={})},ra=function(a,b){var c=a.split("."),d=b||v;for(var e;e=c.shift();)if(d[e])d=d[e];else return i;return d};
var x=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!sa(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},ta=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return m;return h};
if(Object.prototype.propertyIsEnumerable)var sa=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):ta(a,b)};else sa=ta;var pa=function(a){return typeof a!="undefined"};var ua=function(a){var b=x(a);return b=="array"||b=="object"&&typeof a.length=="number"};
var y=function(a){return x(a)=="function"},va=function(a){var b=x(a);return b=="object"||b=="array"||b=="function"},ya=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(wa)){var b=a[wa];if(b)return b}a[wa]||(a[wa]=++xa);return a[wa]},wa="closure_hashCode_",xa=0,z=function(a,b){var c=a.Fb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.Hb||b;a=a.Gb||a;var e,f=b||v;e=c?function(){var g=Array.prototype.slice.call(arguments);g.unshift.apply(g,c);return a.apply(f,
g)}:function(){return a.apply(f,arguments)};e.Fb=c;e.Hb=b;e.Gb=a;return e},za=Date.now||function(){return(new Date).getTime()},Aa=function(a,b,c){qa(a,b,c)},A=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a};var Ba=function(a,b){this.x=pa(a)?a:0;this.y=pa(b)?b:0};Ba.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var B=function(a,b){this.width=a;this.height=b};B.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};B.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};B.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};B.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
B.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Ca=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ia=function(a,b){if(b)return a.replace(Da,"&amp;").replace(Ea,"&lt;").replace(Fa,"&gt;").replace(Ga,"&quot;");else{if(!Ha.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Da,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Ea,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Fa,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Ga,"&quot;");return a}},Da=/&/g,Ea=/</g,Fa=/>/g,Ga=/\"/g,Ha=/[&<>\"]/,Ja=function(a,b){var c=b.length;for(var d=0;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},La=function(a,b){var c=0,d=Ca(String(a)).split("."),e=Ca(String(b)).split("."),f=Math.max(d.length,e.length);for(var g=0;c==0&&g<f;g++){var j=d[g]||"",k=e[g]||"",l=new RegExp("(\\d*)(\\D*)","g"),n=new RegExp("(\\d*)(\\D*)","g");do{var p=l.exec(j)||["","",""],q=n.exec(k)||["","",""];if(p[0].length==0&&q[0].length==0)break;var w=p[1].length==0?0:parseInt(p[1],10),L=q[1].length==0?0:parseInt(q[1],
10);c=Ka(w,L)||Ka(p[2].length==0,q[2].length==0)||Ka(p[2],q[2])}while(c==0)}return c},Ka=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};za();var Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa=function(){if(v.navigator)return v.navigator.userAgent;return i},Ya=function(){var a=h,b=h,c=h,d=h,e=h,f=h,g=h,j=h,k=h,l="",n=Xa();if(n){var p=v.navigator;a=n.indexOf("Opera")==0;b=!a&&n.indexOf("MSIE")!=-1;c=!a&&n.indexOf("WebKit")!=-1;k=c&&n.indexOf("Mobile")!=-1;d=!a&&!c&&p.product=="Gecko";e=d&&p.vendor=="Camino";var q,w;if(v.opera)q=v.opera.version();else{if(d)w=/rv\:([^\);]+)(\)|;)/;else if(b)w=/MSIE\s+([^\);]+)(\)|;)/;else if(c)w=/WebKit\/(\S+)/;if(w){w.test(n);
q=RegExp.$1}}l=p.platform||"";f=l.indexOf("Mac")!=-1;g=l.indexOf("Win")!=-1;j=l.indexOf("Linux")!=-1}Ma=a;Na=b;Oa=d;Pa=e;Qa=c;Ra=k;Sa=q;Ta=l;Ua=f;Va=g;Wa=j};Ya();var Za=Ma,C=Na,db=Oa,D=Qa,eb=Ra;var E=function(a){return La(Sa,a)>=0};var fb=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==i?0:c<0?Math.max(0,a.length+c):c;for(var e=d;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},gb=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=typeof a=="string"?a.split(""):a;for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}},hb=function(a,b){var c=fb(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};
var ib=function(a){if(x(a)=="array")return a.concat();else{var b=[];for(var c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var jb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var kb;var lb=function(){kb||(kb=new F);return kb},nb=function(a){return a?new F(mb(a)):lb()};
var ob=function(a){return typeof a=="string"?document.getElementById(a):a},pb=ob,rb=function(a,b){jb(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in qb)a.setAttribute(qb[d],c);else a[d]=c})},qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder"},sb=function(a){var b=a||v||window,c=b.document;if(D&&!E("500")&&
!eb){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new B(b.innerWidth,d)}var f=nb(c),g=f.$a()=="CSS1Compat"&&(!Za||Za&&E("9.50"))?c.documentElement:c.body;return new B(g.clientWidth,g.clientHeight)};var tb=function(a,b){a.appendChild(b)},ub=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):i};
var vb=D&&La(Sa,"521")<=0,wb=function(a,b){if(typeof a.contains!="undefined"&&!vb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);while(b&&a!=b)b=b.parentNode;return b==a},mb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},xb=function(a){if(a&&typeof a.length=="number")if(va(a))return typeof a.item=="function"||typeof a.item=="string";else if(y(a))return typeof a.item=="function";return h},
F=function(a){this.s=a||v.document||document};F.prototype.ab=function(){return this.s};F.prototype.Oa=function(a,b){if(C&&b&&b.name)a="<"+a+' name="'+Ia(b.name)+'">';var c=this.createElement(a);b&&rb(c,b);if(arguments.length>2){function d(g){if(g)this.appendChild(c,typeof g=="string"?this.createTextNode(g):g)}for(var e=2;e<arguments.length;e++){var f=arguments[e];ua(f)&&!(va(f)&&f.nodeType>0)?gb(xb(f)?ib(f):f,d,this):d.call(this,f)}}return c};F.prototype.createElement=function(a){return this.s.createElement(a)};
F.prototype.createTextNode=function(a){return this.s.createTextNode(a)};F.prototype.$a=function(){if(this.s.compatMode)return this.s.compatMode;if(D){var a=this.Oa("div",{style:"position:absolute;width:0;height:0;width:1"}),b=a.style.width=="1px"?"BackCompat":"CSS1Compat";return this.s.compatMode=b}return"BackCompat"};
F.prototype.oa=function(){var a=this.s,b,c;if(!D&&a.compatMode=="CSS1Compat"){b=a.documentElement.scrollLeft;c=a.documentElement.scrollTop}else{b=a.body.scrollLeft;c=a.body.scrollTop}return new Ba(b,c)};F.prototype.appendChild=tb;F.prototype.removeNode=ub;F.prototype.contains=wb;var yb,zb=function(a,b){var c=mb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return i};
var Ab=function(a){return zb(a,"position")||(a.currentStyle?a.currentStyle.position:i)||a.style.position},Bb=function(a){var b;b=a?a.nodeType==9?a:mb(a):lb().ab();if(C&&b.compatMode!="CSS1Compat")return b.body;return b.documentElement},Cb=function(a){var b=mb(a),c=db&&b.getBoxObjectFor&&Ab(a)=="absolute"&&(a.style.top==""||a.style.left=="");if(typeof yb=="undefined")yb=Pa&&!E("1.8.0.11");var d=new Ba(0,0),e=Bb(b);if(a==e)return d;var f=i,g;if(a.getBoundingClientRect&&!c){g=a.getBoundingClientRect();
var j=nb(b).oa();d.x=g.left+j.x;d.y=g.top+j.y}else if(b.getBoxObjectFor&&!c&&!yb){g=b.getBoxObjectFor(a);var k=b.getBoxObjectFor(e);d.x=g.screenX-k.screenX;d.y=g.screenY-k.screenY}else{f=a;do{d.x+=f.offsetLeft;d.y+=f.offsetTop;if(D&&Ab(f)=="fixed"){d.x+=b.body.scrollLeft;d.y+=b.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(Za||D&&Ab(a)=="absolute")d.y-=b.body.offsetTop;f=a.offsetParent;while(f&&f!=b.body){d.x-=f.scrollLeft;if(!Za||f.tagName!="TR")d.y-=f.scrollTop;f=f.offsetParent}}if(db&&
a.getBoundingClientRect){var l=Ab(a);if(l=="static"||l=="relative"){d.x=Math.floor(d.x);d.y=Math.floor(d.y)}}return d},Db=function(a){var b=new Ba;if(a.nodeType==1)if(a.getBoundingClientRect){var c=a.getBoundingClientRect();b.x=c.left;b.y=c.top}else{var d=nb(a).oa(),e=Cb(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b};db&&!E("1.9");
var Eb=function(a){var b=mb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=zb(a,"fontFamily")||(a.currentStyle?a.currentStyle.fontFamily:i)||a.style.fontFamily;if(Za&&Wa)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Ja(c,"\"'")};var G=function(){};G.prototype.na=h;G.prototype.dispose=function(){if(!this.na){this.b();this.na=m}};G.prototype.b=function(){};var Fb=function(a){if(/^\s*$/.test(a))return h;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Gb=function(a){var b=String(a);if(typeof b.parseJSON=="function")return b.parseJSON();if(Fb(a))try{return eval("("+a+")")}catch(c){}throw Error("Invalid JSON string: "+a);},Hb=i,Ib=function(a){Hb||(Hb=
new H);return Hb.serialize(a)},H=function(){};H.prototype.serialize=function(a){if(a!=i&&typeof a.toJSONString=="function")return a.toJSONString();var b=[];this.Y(a,b);return b.join("")};
H.prototype.Y=function(a,b){switch(typeof a){case "string":this.xa(a,b);break;case "number":this.yb(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==i){b.push("null");break}if(x(a)=="array"){this.xb(a,b);break}this.zb(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};var Jb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"};
H.prototype.xa=function(a,b){b.push('"',a.replace(/[\\\"\x00-\x1f\x80-\uffff]/g,function(c){if(c in Jb)return Jb[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Jb[c]=e+d.toString(16)}),'"')};H.prototype.yb=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};H.prototype.xb=function(a,b){var c=a.length;b.push("[");var d="";for(var e=0;e<c;e++){b.push(d);this.Y(a[e],b);d=","}b.push("]")};
H.prototype.zb=function(a,b){b.push("{");var c="";for(var d in a){var e=a[d];if(typeof e!="function"){b.push(c);this.xa(d,b);b.push(":");this.Y(e,b);c=","}}b.push("}")};var I="SETUP_ACK",Kb={},Mb=function(a,b){var c=b||Lb,d=c.length,e="";while(a-- >0)e+=c.charAt(Math.floor(Math.random()*d));return e},Lb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var Nb=function(){};A(Nb,G);var J=function(a){this.a=a;this.L=[];this.Lb=z(this.Ta,this)};A(J,Nb);J.prototype.l=0;J.prototype.G=1;J.prototype.T=h;J.prototype.Ab=0;J.prototype.connect=function(){this.V=window.parent==this.a.f?this.G:this.l;if(this.V==this.l){this.i=this.a.u;this.i.XPC_toOuter=z(this.pa,this)}else this.ca()};
J.prototype.ca=function(){var a=m;try{if(!this.i)this.i=window.frameElement;if(this.i&&this.i.XPC_toOuter){this.sa=this.i.XPC_toOuter;this.i.XPC_toOuter.XPC_toInner=z(this.pa,this);a=h;this.send("tp",I);this.a.k()}}catch(b){}if(a){if(!this.Ea)this.Ea=z(this.ca,this);window.setTimeout(this.Ea,100)}};J.prototype.D=function(a){if(this.V==this.l&&!this.a.j()&&a==I){this.sa=this.i.XPC_toOuter.XPC_toInner;this.a.k()}else throw Error("Got unexpected transport message.");};
J.prototype.pa=function(a,b){if(!this.T&&this.L.length==0)this.a.m(a,b);else{this.L.push({serviceName:a,payload:b});if(this.L.length==1)this.Ab=window.setTimeout(this.Lb,1)}};J.prototype.Ta=function(){while(this.L.length){var a=this.L.shift();this.a.m(a.serviceName,a.payload)}};J.prototype.send=function(a,b){this.T=m;this.sa(a,b);this.T=h};J.prototype.b=function(){J.o.b.call(this);this.sa=i;this.i=i};var K=function(a){this.a=a;this.M=this.a.c.ppu;this.Ob=this.a.c.lpu;this.W=[]},Ob,Pb,Qb;A(K,Nb);K.prototype.X=0;K.prototype.z=h;K.prototype.connect=function(){this.Ma()};K.prototype.Ma=function(){var a=this.a.name+"_msg";this.jb=this.ha(a);this.mb=window.frames[a];a=this.a.name+"_ack";this.Ba=this.ha(a);this.Da=window.frames[a];this.ea()};
K.prototype.ha=function(a){var b=lb().createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.id=b.name=a;b.src=this.M+"#INITIAL";document.body.appendChild(b);return b};
K.prototype.ea=function(){this.Ia&&window.clearTimeout(this.Ia);if(this.qa("msg")&&this.qa("ack")){this.kb=new Rb(this,this.a.f.frames[this.a.name+"_msg"],z(this.qb,this));this.Ca=new Rb(this,this.a.f.frames[this.a.name+"_ack"],z(this.pb,this));this.ga()}else{if(!this.Ha)this.Ha=z(this.ea,this);this.Ia=window.setTimeout(this.Ha,100)}};K.prototype.qa=function(a){try{var b=this.a.f.frames[this.a.name+"_"+a];if(!b||b.location.href.indexOf(this.Ob)!=0)return h}catch(c){return h}return m};
K.prototype.ga=function(){var a=this.a.f.frames;if(a[this.a.name+"_ack"]&&a[this.a.name+"_msg"]){this.lb=new Sb(this.M,this.mb);this.O=new Sb(this.M,this.Da);window.setTimeout(z(function(){this.lb.send("SETUP");this.Rb=m;this.z=m},this),100)}else{if(!this.Ja)this.Ja=z(this.ga,this);window.setTimeout(this.Ja,100)}};K.prototype.fa=function(){if(this.wb&&this.Pb){this.a.k();if(this.I){for(var a=0,b;a<this.I.length;a++){b=this.I[a];this.a.m(b.service,b.payload)}delete this.I}}};
K.prototype.qb=function(a){if(a=="SETUP"){if(!this.O)return;this.O.send(I);this.wb=m;this.fa()}else if(this.a.j()||this.wb){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.O.send("ACK:"+e);this.la(d)}else{var e=c.substring(0,b);this.O.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.ta=[];this.ta.push(d);if(f[0]==f[1]){this.la(this.ta.join(""));delete this.ta}}}};
K.prototype.pb=function(a){if(a==I){this.z=h;this.Pb=m;this.fa()}else if(this.a.j()){if(!this.z)return;var b=parseInt(a.split(":")[1],10);if(b==this.X){this.z=h;this.wa()}}};K.prototype.wa=function(){if(this.z||!this.W.length)return;var a=this.W.shift();++this.X;this.lb.send(this.X+a);this.z=m};K.prototype.la=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.j()?this.a.m(c,d):(this.I||(this.I=[])).push({service:c,payload:d})};K.prototype.H=3800;
K.prototype.send=function(a,b){var c=a+":"+b;if(!C||b.length<=this.H)this.W.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.H),f=0,g=1;while(f<d){this.W.push(","+g+"/"+e+"|"+c.substr(f,this.H));g++;f+=this.H}}this.wa()};K.prototype.b=function(){K.o.b.call(this);var a=Tb;hb(a,this.kb);hb(a,this.Ca);this.kb=this.Ca=i;ub(this.jb);ub(this.Ba);this.jb=this.Ba=i;this.mb=this.Da=i};
var Tb=[],Xb=function(){var a=h;try{for(var b=0,c=Tb.length;b<c;b++)a=a||Tb[b].receive()}catch(d){Tb[b].e.a.nb();if(!Tb.length)return}var e=za();if(a)Ob=e;var f=e-Ob<1000?10:100;Pb=window.setTimeout(Ub,f)},Ub=z(Xb,K),Yb=function(){Ob=za();Pb&&window.clearTimeout(Pb);Pb=window.setTimeout(Ub,10)},Sb=function(a,b){this.M=a;this.vb=b;this.ka=0};
Sb.prototype.send=function(a){this.ka=++this.ka%2;var b=this.M+"#"+this.ka+encodeURIComponent(a);try{if(D)this.vb.location.href=b;else this.vb.location.replace(b)}catch(c){}Qb=za()};var Rb=function(a,b,c){this.e=a;this.rb=b;this.Ib=c;this.Ra=this.rb.location.href.split("#")[0]+"#INITIAL";Tb.push(this);Yb()};Rb.prototype.receive=function(){var a=this.rb.location.href;if(a!=this.Ra){this.Ra=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Ib(decodeURIComponent(b))}return m}else return h};var M=function(a,b){G.call(this);this.hb=b;this.t=[];this.Pa(a)};A(M,G);M.prototype.P=i;M.prototype.Q=i;M.prototype.C=function(a){this.P=a};M.prototype.za=function(a){this.Q=a};M.prototype.h=function(){if(this.t.length)return this.t.pop();return this.ja()};M.prototype.w=function(a){this.t.length<this.hb?this.t.push(a):this.ma(a)};M.prototype.Pa=function(a){if(a>this.hb)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.t.push(this.ja())};
M.prototype.ja=function(){return this.P?this.P():{}};M.prototype.ma=function(a){if(this.Q)this.Q(a);else if(y(a.dispose))a.dispose();else for(var b in a)delete a[b]};M.prototype.b=function(){M.o.b.call(this);var a=this.t;while(a.length)this.ma(a.pop());delete this.t};var N=function(a,b){this.type=a;this.target=b;this.currentTarget=this.target};A(N,G);N.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};N.prototype.B=h;N.prototype.U=m;N.prototype.stopPropagation=function(){this.B=m};N.prototype.preventDefault=function(){this.U=h};var O=function(a,b){a&&this.init(a,b)};A(O,N);O.prototype.type=i;O.prototype.target=i;O.prototype.relatedTarget=i;O.prototype.offsetX=0;O.prototype.offsetY=0;O.prototype.clientX=0;O.prototype.clientY=0;O.prototype.screenX=0;O.prototype.screenY=0;O.prototype.button=0;O.prototype.keyCode=0;O.prototype.charCode=0;O.prototype.ctrlKey=h;O.prototype.altKey=h;O.prototype.shiftKey=h;O.prototype.metaKey=h;O.prototype.g=i;
O.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:i;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.g=a;delete this.U;delete this.B};O.prototype.stopPropagation=function(){this.B=m;if(this.g.stopPropagation)this.g.stopPropagation();else this.g.cancelBubble=m};
O.prototype.preventDefault=function(){this.U=h;if(this.g.preventDefault)this.g.preventDefault();else{this.g.returnValue=h;try{this.g.keyCode=-1}catch(a){}}};O.prototype.Za=function(){return this.g};O.prototype.b=function(){O.o.b.call(this);this.g=i};var P=function(){},Zb=0;P.prototype.S=i;P.prototype.listener=i;P.prototype.proxy=i;P.prototype.src=i;P.prototype.type=i;P.prototype.capture=i;P.prototype.handler=i;P.prototype.key=0;P.prototype.removed=h;P.prototype.da=h;P.prototype.init=function(a,b,c,d,e,f){if(y(a))this.S=m;else if(a&&a.handleEvent&&y(a.handleEvent))this.S=h;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.da=h;this.key=++Zb;this.removed=h};
P.prototype.handleEvent=function(a){if(this.S)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var $b={},Q={},ac={},bc=new M(0,600);bc.C(function(){return{r:0}});bc.za(function(a){a.r=0});var R=new M(0,600);R.C(function(){return[]});R.za(function(a){a.length=0;delete a.K;delete a.ra});var cc=new M(0,600);cc.C(function(){var a=function(b){return dc.call(a.src,a.key,b)};return a});var ec=function(){return new P},fc=new M(0,600);fc.C(ec);
var gc=function(){return new O},hc=function(){var a=i;if(C){a=new M(0,600);a.C(gc)}return a},ic=hc(),jc="on",kc={},lc=function(a,b,c,d,e){if(b)if(x(b)=="array"){for(var f=0;f<b.length;f++)lc(a,b[f],c,d,e);return i}else{var g=!!d,j=Q;b in j||(j[b]=bc.h());j=j[b];if(!(g in j)){j[g]=bc.h();j.r++}j=j[g];var k=ya(a),l,n;if(j[k]){l=j[k];for(var f=0;f<l.length;f++){n=l[f];if(n.listener==c&&n.handler==e){if(n.removed)break;return l[f].key}}}else{l=j[k]=R.h();j.r++}var p=cc.h();p.src=a;n=fc.h();n.init(c,p,
a,b,g,e);var q=n.key;p.key=q;l.push(n);$b[q]=n;ac[k]||(ac[k]=R.h());ac[k].push(n);if(a.addEventListener){if(a==v||!a.Kb)a.addEventListener(b,p,g)}else a.attachEvent(mc(b),p);return q}else throw Error("Invalid event type");},nc=function(a,b,c,d,e){if(x(b)=="array"){for(var f=0;f<b.length;f++)nc(a,b[f],c,d,e);return i}var g=!!d,j=oc(a,b,g);if(!j)return h;for(var f=0;f<j.length;f++)if(j[f].listener==c&&j[f].capture==g&&j[f].handler==e)return pc(j[f].key);return h},pc=function(a){if(!$b[a])return h;var b=
$b[a];if(b.removed)return h;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==v||!c.Kb)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(mc(d),e);var g=ya(c),j=Q[d][f][g];if(ac[g]){var k=ac[g];hb(k,b);k.length==0&&delete ac[g]}b.removed=m;j.ra=m;qc(d,f,g,j);delete $b[a];return m},qc=function(a,b,c,d){if(!d.K)if(d.ra){for(var e=0,f=0;e<d.length;e++){if(d[e].removed){fc.w(d[e]);continue}if(e!=f)d[f]=d[e];f++}d.length=f;d.ra=h;if(f==0){R.w(d);delete Q[a][b][c];Q[a][b].r--;
if(Q[a][b].r==0){bc.w(Q[a][b]);delete Q[a][b];Q[a].r--}if(Q[a].r==0){bc.w(Q[a]);delete Q[a]}}}},oc=function(a,b,c){var d=Q;if(b in d){d=d[b];if(c in d){d=d[c];var e=ya(a);if(d[e])return d[e]}}return i},mc=function(a){if(a in kc)return kc[a];return kc[a]=jc+a},sc=function(a,b,c,d){var e=1,f=Q;if(b in f){f=f[b];if(c in f){f=f[c];var g=ya(a);if(f[g]){var j=f[g];if(j.K)j.K++;else j.K=1;try{var k=j.length;for(var l=0;l<k;l++){var n=j[l];if(n&&!n.removed)e&=rc(n,d)!==h}}finally{j.K--;qc(b,c,g,j)}}}}return Boolean(e)},
rc=function(a,b){var c=a.handleEvent(b);a.da&&pc(a.key);return c},dc=function(a,b){if(!$b[a])return m;var c=$b[a],d=c.type,e=Q;if(!(d in e))return m;e=e[d];var f;if(C){var g=b||ra("window.event"),j=m in e;if(j){if(g.keyCode<0||g.returnValue!=undefined)return m;tc(g)}ya(c.src);var k=ic.h();k.init(g,this);f=m;try{if(j){var l=R.h();for(var n=k.currentTarget;n;n=n.parentNode)l.push(n);for(var p=l.length-1;!k.B&&p>=0;p--){k.currentTarget=l[p];f&=sc(l[p],d,m,k)}for(var p=0;!k.B&&p<l.length;p++){k.currentTarget=
l[p];f&=sc(l[p],d,h,k)}}else f=rc(c,k)}finally{if(l){l.length=0;R.w(l)}k.dispose();ic.w(k)}return f}var q=new O(b,this);try{f=rc(c,q)}finally{q.dispose()}return f},tc=function(a){var b=h;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=m}if(b||a.returnValue==undefined)a.returnValue=m};var S=function(a){this.a=a;this.Nb=this.a.c.pru;this.ob=this.a.c.ifrid;D&&uc()};A(S,Nb);if(D){var vc=[],wc=0,uc=function(){wc||(wc=window.setTimeout(function(){xc()},1000))},xc=function(a){var b=za(),c=a||3000;while(vc.length&&b-vc[0].timestamp>=c){var d=vc.shift().iframeElement;ub(d)}wc=window.setTimeout(yc,1000)},yc=function(){xc()}}S.prototype.connect=function(){this.send("tp","SETUP")};S.prototype.D=function(a){if(a=="SETUP"){this.send("tp",I);this.a.k()}else a==I&&this.a.k()};
S.prototype.send=function(a,b){if(C){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=zc}else{var d=document.createElement("iframe");D?vc.push({timestamp:za(),iframeElement:d}):lc(d,"load",zc)}var e=d.style;e.visibility="hidden";e.width=d.style.height="0px";e.position="absolute";var f=this.Nb;f+="#"+this.a.name;if(this.ob)f+=","+this.ob;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var zc=function(){ub(this);this.xpcOnload=i};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);Kb[a].m(d,decodeURIComponent(e))};S.prototype.b=function(){S.o.b.call(this);D&&xc(0)};var T=function(a){this.a=a};A(T,Nb);var Ac=h,Cc=function(){if(!Ac){lc(y(window.postMessage)?window:document,"message",Bc,h,T);Ac=m}},Bc=function(a){var b=a.Za().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return;var e=b.substring(0,c),f=b.substring(c+1,d),g=b.substring(d+1),j=Kb[e];j&&j.m(f,g)};T.prototype.D=function(a){switch(a){case "SETUP":this.send("tp",I);case I:this.a.k();break}};T.prototype.connect=function(){Cc();this.send("tp","SETUP")};
T.prototype.send=function(a,b){var c=this.a.f;if(!c)return;var d=y(window.postMessage)?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,"*")};this.send(a,b)};T.prototype.b=function(){T.o.b.call(this);nc(document,"message",this.Qb,h,this)};var U=function(a){this.a=a;this.Fa=a.at||"";this.ub=a.rat||"";Dc();this[Ec]=this.J;this[Fc]=this.Na};A(U,Nb);
var Gc="GRPC____NIXVBS_wrapper",Hc="GRPC____NIXVBS_get_wrapper",Ec="GRPC____NIXJS_handle_message",Fc="GRPC____NIXJS_create_channel",Ic="GRPC____NIXVBS_container",Dc=function(){if(window.nix_setup_complete)return;var a="Class "+Gc+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Ec+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Fc+"(channel)\nEnd Sub\nPublic Sub "+Ic+"()\n End Sub\nEnd Class\n Function "+Hc+"(transport, auth)\nDim wrap\nSet wrap = New "+Gc+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Hc+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=m}catch(b){}};U.prototype.l=0;U.prototype.G=1;U.prototype.v=h;U.prototype.n=i;
U.prototype.connect=function(){this.V=window.parent==this.a.f?this.G:this.l;this.V==this.l?this.ba():this.aa()};U.prototype.ba=function(){if(this.v)return;var a=this.a.u;try{a.contentWindow.opener=window[Hc](this,this.Fa);this.v=m}catch(b){}this.v||window.setTimeout(z(this.ba,this),100)};
U.prototype.aa=function(){if(this.v)return;try{var a=window.opener;if(a&&Ic in a){this.n=a;var b=this.n.GetAuthToken();if(b!=this.ub)return;this.n.CreateChannel(window[Hc](this,this.Fa));this.v=m;this.a.k()}}catch(c){return}this.v||window.setTimeout(z(this.aa,this),100)};U.prototype.Na=function(a){this.n=a;var b=this.n.GetAuthToken();if(b!=this.ub)return;this.a.k()};U.prototype.J=function(a,b){function c(){this.a.m(a,b)}window.setTimeout(z(c,this),1)};
U.prototype.send=function(a,b){this.n.SendMessage(a,b)};U.prototype.b=function(){U.o.b.call(this);this.n=i};var V=function(a){this.c=a;this.name=this.c.cn||Mb(10);this.ya={};Kb[this.name]=this;lc(window,"unload",Jc)};A(V,G);V.prototype.e=i;V.prototype.Z=1;V.prototype.j=function(){return this.Z==2};V.prototype.f=i;V.prototype.u=i;V.prototype.Aa=function(a){this.f=a};
V.prototype.Qa=function(){if(this.e)return;if(!this.c.tp)if(y(document.postMessage)||y(window.postMessage))this.c.tp=1;else if(db)this.c.tp=2;else if(C&&this.c.pru)this.c.tp=3;else if(C)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.e=new T(this);break;case 6:this.e=new U(this);break;case 2:this.e=new J(this);break;case 3:this.e=new S(this);break;case 4:this.e=new K(this);break}if(!this.e)throw Error("CrossPageChannel: No suitable transport found!");};
V.prototype.Sa=h;V.prototype.La=h;V.prototype.connect=function(a){this.Jb=a;if(this.Sa){this.La=m;return}if(this.c.ifrid)this.u=typeof this.c.ifrid=="string"?document.getElementById(this.c.ifrid):this.c.ifrid;if(this.u){var b=this.u.contentWindow;b||(b=window.frames[this.c.ifrid]);this.Aa(b)}if(!this.f)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.Aa(window.parent);this.Qa();this.e.connect()};
V.prototype.close=function(){if(!this.j())return;this.Z=3;this.e.dispose();this.e=i};V.prototype.k=function(){if(this.j())return;this.Z=2;this.Jb()};V.prototype.nb=function(){this.close()};V.prototype.tb=function(a,b,c){this.ya[a]={name:a,callback:b,jsonEncoded:!!c}};V.prototype.send=function(a,b){if(!this.j())return;if(this.f.closed){this.close();return}if(va(b))b=Ib(b);this.e.send(a,b)};
V.prototype.m=function(a,b){if(!a||a=="tp")this.e.D(b);else if(this.j()){var c=this.ya[a];if(c){if(c.jsonEncoded)try{b=Gb(b)}catch(d){return}c.callback(b)}}};V.prototype.b=function(){V.o.b.call(this);this.close();this.f=i;this.u=i;delete this.ya;Kb[this.name]=i};var Jc=function(){for(var a in Kb){var b=Kb[a];b&&b.dispose()}};var Kc=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var W=function(a,b){this.q=b.width;this.p=b.height;this.Ga=Mb(10);this.Mb=this.bb(a,document);this.R=h;this.d=b;this.d.src=this.ib(document,a);this.gb(this.db(document))};W.prototype.ib=function(a,b){return b+(b.indexOf("?")==-1?"?":"&")+"w="+this.q+"&h="+this.p+"&xpc="+this.Ga+"&p="+escape(a.location.protocol+"//"+a.location.host)};W.prototype.db=function(){var a={};a.ifrid=this.d.id;a.pu=this.d.src;a.cn=this.Ga;a.ppu=Kc(this.Mb);a.lpu=Kc();return a};
W.prototype.gb=function(a){this.a=new V(a);this.a.tb("expandable_ad",z(this.J,this));this.a.connect(function(){})};W.prototype.bb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,g=f.indexOf("/");if(d&&g>0)f=f.substring(0,g);return e+"//"+f};W.prototype.J=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.fb(b);else c=="collapse"&&this.eb()};W.prototype.va=function(a){this.a.send("expandable_ad",a)};
W.prototype.fb=function(a){if(this.R)return;var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.Ua(b,c);this.Wa(b,c,f);this.va("ok_expand_w"+b+"_h"+c+"_d"+f)};W.prototype.eb=function(){if(!this.R)return;this.Ka();this.va("ok_collapse_w"+this.q+"_h"+this.p)};
W.prototype.Ka=function(){this.d.style.width=this.q+"px";this.d.style.height=this.p+"px";this.d.style.left="0";this.d.style.top="0";this.d.style.zIndex=i;this.d.parentNode.style.zIndex=i;this.R=h};
W.prototype.Wa=function(a,b,c){this.d.style.position="absolute";this.d.style.width=a+"px";this.d.style.height=b+"px";this.d.style.zIndex=9999;this.d.parentNode.style.zIndex=9999;if(a>this.q&&(c==0||c==3))this.d.style.left="-"+(a-this.q)+"px";if(b>this.p&&(c==1||c==0))this.d.style.top="-"+(b-this.p)+"px";this.R=m};
W.prototype.Ua=function(a,b){var c=Db(this.d),d=sb(window),e=a-this.q,f=b-this.p,g=c.y,j=f>g,k=d.height-(c.y+this.p),l=j||k>=g,n=c.x,p=e>n,q=d.width-(c.x+this.q),w=p||q>=n,L=0;if(l&&w)L=2;else if(l&&!w)L=3;else if(!l&&w)L=1;else if(!l&&!w)L=0;return L};Aa("ExpandableAdSlot",W);var Lc=0;function Mc(a){return a!=i?'"'+a+'"':'""'}function la(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=fa[a]||ga[a]||i,d=b[a];X(c,d)}function Z(a,b){b!=i&&X(a,la(b))}function $(a){var b=window,c=fa[a]||ga[a]||i,d=b[a];Z(c,d)}function Nc(a,b){var c=window,d=fa[a]||ga[a]||i,e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}
function Oc(a,b){var c=a.screen,d=navigator.javaEnabled(),e=-b.getTimezoneOffset();if(c){X("u_h",c.height);X("u_w",c.width);X("u_ah",c.availHeight);X("u_aw",c.availWidth);X("u_cd",c.colorDepth)}X("u_tz",e);X("u_his",history.length);X("u_java",d);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function Pc(a){if(!a.google_enable_first_party_cookie)return;if(t==i)t=new ha;if(a._GA_googleCookieHelper==i)a._GA_googleCookieHelper=new u;if(!a._google_cookie_fetched){a._google_cookie_fetched=m;a._GA_googleCookieHelper.Xa(Qc(a.google_ad_client))}}function Qc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Rc(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function Sc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}function Tc(){var a=C&&E("6")&&!E("8"),b=db&&E("1.8.1"),c=D&&E("525");if(Va&&(a||b||c))return m;else if(Ua&&(c||b))return m;else if(Wa&&b)return m;return h}function Uc(a,b){var c=a.google_allow_expandable_ads;if(c!=i&&c==h||Vc(a,b)||Wc(a)||Xc(a.google_ad_format)||!Tc())return h;return m}function Yc(){var a=Math.random();if(a<0.03)return 30143001;else if(a<0.06)return 30143002;return 0}
function Zc(a){a.google_allow_expandable_ads=h}var $c=Math.random()<0.0010;function ad(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function bd(a,b,c,d){var e=Sc(a),f=a.google_container_id||d||"google_ad_div"+e;c=c.substring(0,2000);c=c.replace(/%\w?$/,"");var g="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+g+' language="JavaScript1.1" src='+Mc(c)+"></"+g+">");else if(a.google_ad_output=="html")if(a.google_expandable_iframe||Lc==30143002){var j=cd(f,parseInt(a.google_ad_width,10),parseInt(a.google_ad_height,10),b),k=dd(e,a,j);a["google_expandable_ad_slot"+
e]=new W(c,k)}else{var l='<iframe name="google_ads_frame" width='+Mc(a.google_ad_width)+" height="+Mc(a.google_ad_height)+" frameborder="+Mc(a.google_ad_frameborder)+" src="+Mc(c)+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?ed(a.google_container_id,b,l):b.write(l)}else a.google_ad_output=="textlink"&&b.write("<"+g+' language="JavaScript1.1" src='+Mc(c)+"></"+g+">");if($c){var n=fd(a)+"/pagead/gen_204?id=ifjs&token="+
a.google_correlator;ad(a,n)}}function cd(a,b,c,d){var e=pb(a);if(e){e.style.display="block";e.style.height=c+"px";e.style.visibility="visible";e.style.width=b+"px"}else{d.write('<ins id="'+a+'" style="width:'+b+"px;height:"+c+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none"></ins>');e=pb(a)}return e}
function dd(a,b,c){var d=lb().createElement("IFRAME");d.id="google_ads_frame"+a;d.allowTransparency=m;d.frameBorder=b.google_ad_frameborder||0;d.height=b.google_ad_height;d.hspace=0;d.marginHeight=0;d.marginWidth=0;d.name="google_ads_frame";d.scrolling="no";d.style.left=0;d.style.position="absolute";d.style.top=0;d.vspace=0;d.width=b.google_ad_width;c.appendChild(d);return d}function gd(a){for(var b in fa)a[b]=i;for(var b in ga){if(b=="google_correlator")continue;a[b]=i}a.google_container_id=i}
function Wc(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function Xc(a){return a&&a.indexOf("_sdo")!=-1}
function hd(a){var b=i,c=window,d=document,e=new Date,f=e.getTime(),g=c.google_ad_format,j=fd(c);if(c.google_cpa_choice!=b){c.google_ad_url=j+"/cpa/ads?";c.google_ad_url+="client="+escape(Qc(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if(Xc(g)){c.google_ad_url=j+"/pagead/sdo?";c.google_ad_url+="client="+escape(Rc(c.google_ad_client))}else{c.google_ad_url=
j+"/pagead/ads?";c.google_ad_url+="client="+escape(Qc(c.google_ad_client))}Y("google_ad_host");Y("google_ad_host_tier_id");var k=c.google_num_slots_by_client,l=c.google_num_slots_by_channel,n=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if(Xc(g)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>
4)return h}else if(Wc(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return h}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){n[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=f%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return h}else if(c.google_num_ad_slots>6&&q=="")return h}X("dt",e.getTime());
Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var w=c.google_ad_client;if(k[w])k[w]+=1;else{k[w]=1;k.length+=1}if(n[q])if(!Xc(g)){Z("prev_fmts",n[q].toLowerCase());k.length>1&&X("slot",k[w])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(g&&!c.google_ad_slot){Z("format",
g.toLowerCase());Xc(g)||(n[q]=n[q]?n[q]+","+g:g)}if(c.google_ad_slot)p[q]=p[q]?p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var L="",Vb=c.google_ad_channel.split(/[+, ]/);for(var $a=0;$a<Vb.length;$a++){var ab=Vb[$a];if(l[ab])L+=ab+"+";else l[ab]=
1}Z("pv_ch",L)}if(c.google_ad_host_channel){$("google_ad_host_channel");var pd=id(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",pd)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.cb());$("google_page_url");Nc("google_color_bg",f);Nc("google_color_text",f);Nc("google_color_link",f);Nc("google_color_url",f);Nc("google_color_border",f);Nc("google_color_line",f);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");
$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");if(!Uc(c,d))Zc(c);else if(c.google_expandable_iframe===h)Zc(c);else if(!(c.google_expandable_iframe==m)){Lc=Yc();X("eid",Lc);Lc!=30143002&&Zc(c)}var Wb=c.google_allow_expandable_ads;if(Wb!=i)Wb?X("ea","1"):X("ea","0");Y("google_feedback");$("google_referrer_url");
$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");$("google_only_ads_with_video");$("google_disable_video_autoplay");if(a){Z("ff",Eb(a));var bb=Cb(a),cb=sb();if(bb&&cb){Z("biw",
cb.width);Z("bih",cb.height);Z("adx",bb.x);Z("ady",bb.y)}}aa();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");Oc(c,e);$c&&X("gen_204","yes");return m}
function id(a,b){var c=a.split("|"),d=-1,e=[];for(var f=0;f<c.length;f++){var g=c[f].split(/[+, ]/);b[f]||(b[f]={});var j="";for(var k=0;k<g.length;k++){var l=g[k];if(b[f][l])j+="+"+l;else b[f][l]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var n="";if(d>-1){for(var f=0;f<d;f++)n+=e[f]+"|";n+=e[d]}return n}
function jd(){var a=window,b=document;Pc(a);var c;if(Math.random()<0.01){var d="google_temp_span";if(!pb(d)){b.write("<span id="+d+"></span>");c=pb(d)}}var e=hd(c);c&&ub(c);if(!e)return;bd(a,b,a.google_ad_url);gd(a)}function kd(){jd();return m}
function Vc(a,b){var c=b.documentElement;if(a.top.location==b.location)return h;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return h}return m}
function ld(a){var b=window,c=i,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(Xc(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;md(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=(new Date).getTime();if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot=
{};if(b.google_flash_version==c)b.google_flash_version=ma();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function na(a){if(a in nd)return nd[a];return nd[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var nd={};
function od(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(g){}}return b}function qd(){var a=window,b=od(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function rd(a,b){for(var c in b)a["google_"+c]=b[c]}
function sd(a,b){if(!b)return a.location;return a.referrer}function td(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function ud(a,b,c,d){a.page_url=sd(c,d);a.page_location=i}function vd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=sd(c,d)||"EMPTY"}
function wd(a,b){var c={},d=Vc(a,b);c.iframing=td(a,d);!!a.google_page_url?vd(c,a,b,d):ud(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function xd(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.location;b.last_modified_time=i;b.referrer_url=c;return b}
function md(a,b){var c;c=a.google_page_url==i&&yd[b.domain]?xd(b):wd(a,b);rd(a,c)}function ed(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var yd={};yd["ad.yieldmanager.com"]=m;window.google_render_ad=jd;var zd={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Ad(a){var b=a.google_page_location||a.google_page_url;if(!b)return h;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=h;if(e.length>=3)f=e[e.length-3]in zd;if(e.length>=2)f=f||e[e.length-2]in zd;return f}
function Bd(a,b,c){if(a.google_new_domain_checked==0){a.google_random_number=Math.random();if(a.google_random_number<c){var d="http://googleads.g.doubleclick.net/pagead/test_domain.js",e="script";b.write("<"+e+' src="'+d+'"></'+e+">");a.google_new_domain_checked=1}}}function fd(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Ad(a)&&a.google_new_domain_enabled==1)return b;return c};qd();ld(kd);Bd(window,document,0.01);var Cd="script";document.write("<"+Cd+"> window.google_render_ad(); </"+Cd+">");
})()
