//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteBPEL.AlmacenBPEL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mtis.org/BPEL/", ConfigurationName="AlmacenBPEL.AlmacenBPELPortType")]
    public interface AlmacenBPELPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación comprar no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mtis.org/BPEL/comprar", ReplyAction="http://www.mtis.org/BPEL/AlmacenBPEL/comprarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteBPEL.AlmacenBPEL.comprarResponse comprar(ClienteBPEL.AlmacenBPEL.comprarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mtis.org/BPEL/comprar", ReplyAction="http://www.mtis.org/BPEL/AlmacenBPEL/comprarResponse")]
        System.Threading.Tasks.Task<ClienteBPEL.AlmacenBPEL.comprarResponse> comprarAsync(ClienteBPEL.AlmacenBPEL.comprarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mtis.org/BPEL/")]
    public partial class AlmacenBPELRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenciaField;
        
        private int unidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("unidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mtis.org/BPEL/")]
    public partial class AlmacenBPELResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mtis.org/BPEL/", Order=0)]
        public ClienteBPEL.AlmacenBPEL.AlmacenBPELRequest AlmacenBPELRequest;
        
        public comprarRequest() {
        }
        
        public comprarRequest(ClienteBPEL.AlmacenBPEL.AlmacenBPELRequest AlmacenBPELRequest) {
            this.AlmacenBPELRequest = AlmacenBPELRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mtis.org/BPEL/", Order=0)]
        public ClienteBPEL.AlmacenBPEL.AlmacenBPELResponse AlmacenBPELResponse;
        
        public comprarResponse() {
        }
        
        public comprarResponse(ClienteBPEL.AlmacenBPEL.AlmacenBPELResponse AlmacenBPELResponse) {
            this.AlmacenBPELResponse = AlmacenBPELResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenBPELPortTypeChannel : ClienteBPEL.AlmacenBPEL.AlmacenBPELPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenBPELPortTypeClient : System.ServiceModel.ClientBase<ClienteBPEL.AlmacenBPEL.AlmacenBPELPortType>, ClienteBPEL.AlmacenBPEL.AlmacenBPELPortType {
        
        public AlmacenBPELPortTypeClient() {
        }
        
        public AlmacenBPELPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenBPELPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenBPELPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenBPELPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteBPEL.AlmacenBPEL.comprarResponse ClienteBPEL.AlmacenBPEL.AlmacenBPELPortType.comprar(ClienteBPEL.AlmacenBPEL.comprarRequest request) {
            return base.Channel.comprar(request);
        }
        
        public ClienteBPEL.AlmacenBPEL.AlmacenBPELResponse comprar(ClienteBPEL.AlmacenBPEL.AlmacenBPELRequest AlmacenBPELRequest) {
            ClienteBPEL.AlmacenBPEL.comprarRequest inValue = new ClienteBPEL.AlmacenBPEL.comprarRequest();
            inValue.AlmacenBPELRequest = AlmacenBPELRequest;
            ClienteBPEL.AlmacenBPEL.comprarResponse retVal = ((ClienteBPEL.AlmacenBPEL.AlmacenBPELPortType)(this)).comprar(inValue);
            return retVal.AlmacenBPELResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteBPEL.AlmacenBPEL.comprarResponse> ClienteBPEL.AlmacenBPEL.AlmacenBPELPortType.comprarAsync(ClienteBPEL.AlmacenBPEL.comprarRequest request) {
            return base.Channel.comprarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteBPEL.AlmacenBPEL.comprarResponse> comprarAsync(ClienteBPEL.AlmacenBPEL.AlmacenBPELRequest AlmacenBPELRequest) {
            ClienteBPEL.AlmacenBPEL.comprarRequest inValue = new ClienteBPEL.AlmacenBPEL.comprarRequest();
            inValue.AlmacenBPELRequest = AlmacenBPELRequest;
            return ((ClienteBPEL.AlmacenBPEL.AlmacenBPELPortType)(this)).comprarAsync(inValue);
        }
    }
}
